#  kubectl apply -f .\services\authoriser\
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authoriser-server
  labels:
    app: authoriser-server
spec:
  replicas: 1
  template:
    metadata:
      name: authoriser-server
      labels:
        app: authoriser-server
    spec:
      containers:
        - name: authoriser-server
          image: mayurlomate/websocket-authoriser:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: authoriser-server